/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    becameAVolunteer: BecameAVolunteer;
    explore: Explore;
    startupChennai: StartupChennai;
    funChennai: FunChennai;
    socialChennai: SocialChennai;
    globalSearch: GlobalSearch;
    chennaiInvestments: ChennaiInvestments;
    'events-calendar-block': EventsCalendarBlock;
    volunteerBanner: VolunteerBanner;
    volunteerContentBlock: VolunteerContentBlock;
    volunteerBecameSection: VolunteerBecameSection;
    workBanner: WorkBanner;
    workinchennai: Workinchennai;
    investBanner: InvestBanner;
    investChennai: InvestChennai;
    investmentCategoryList: InvestmentCategoryList;
    liveBanner: LiveBanner;
    livingInChennai: LivingInChennai;
    chennaiLifeEssentials: ChennaiLifeEssentials;
    accodomationBanner: AccodomationBanner;
    HotelInChennai: HotelInChennai;
    exploreMoreChennai: ExploreMoreChennai;
    visitIntroText: VisitIntroText;
    visitBanner: VisitBanner;
  };
  collections: {
    users: User;
    media: Media;
    pages: Page;
    volunteerSlides: VolunteerSlide;
    'investment-categories': InvestmentCategory;
    eventGroups: EventGroup;
    'social-reels': SocialReel;
    visitItems: VisitItem;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    volunteerSlides: VolunteerSlidesSelect<false> | VolunteerSlidesSelect<true>;
    'investment-categories': InvestmentCategoriesSelect<false> | InvestmentCategoriesSelect<true>;
    eventGroups: EventGroupsSelect<false> | EventGroupsSelect<true>;
    'social-reels': SocialReelsSelect<false> | SocialReelsSelect<true>;
    visitItems: VisitItemsSelect<false> | VisitItemsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "becameAVolunteer".
 */
export interface BecameAVolunteer {
  heading: string;
  title: string;
  description?: string | null;
  volunteerSlidesRef: number | VolunteerSlide;
  id?: string | null;
  blockName?: string | null;
  blockType: 'becameAVolunteer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteerSlides".
 */
export interface VolunteerSlide {
  id: number;
  title: string;
  slides?:
    | {
        slug: string;
        image: number | Media;
        title: string;
        subtitle?: string | null;
        description?: string | null;
        detailedContent?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        video?: string | null;
        faq?:
          | {
              question?: string | null;
              answer?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add custom content for this volunteer slide.
   */
  content?: string | null;
  /**
   * SEO metadata for the volunteer slide.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKeywords?: string | null;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "explore".
 */
export interface Explore {
  cards: {
    title: string;
    place: string;
    image: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'explore';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "startupChennai".
 */
export interface StartupChennai {
  heading?: string | null;
  description?: string | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'startupChennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funChennai".
 */
export interface FunChennai {
  heading: string;
  subheading: string;
  cards: {
    title: string;
    place: string;
    image: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'funChennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialChennai".
 */
export interface SocialChennai {
  heading: string;
  description: string;
  reelsRef: number | SocialReel;
  id?: string | null;
  blockName?: string | null;
  blockType: 'socialChennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-reels".
 */
export interface SocialReel {
  id: number;
  title: string;
  reels?:
    | {
        thumbnail: number | Media;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "globalSearch".
 */
export interface GlobalSearch {
  placeholderText: string;
  buttonText: string;
  enableFilters?: boolean | null;
  filters?:
    | {
        label: string;
        options?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'globalSearch';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chennaiInvestments".
 */
export interface ChennaiInvestments {
  heading: string;
  subheading?: string | null;
  categorySource?: (number | InvestmentCategory)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'chennaiInvestments';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-categories".
 */
export interface InvestmentCategory {
  id: number;
  name: string;
  items?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-calendar-block".
 */
export interface EventsCalendarBlock {
  heading: string;
  description?: string | null;
  eventGroupRef: number | EventGroup;
  id?: string | null;
  blockName?: string | null;
  blockType: 'events-calendar-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventGroups".
 */
export interface EventGroup {
  id: number;
  title: string;
  events?:
    | {
        image: number | Media;
        title: string;
        description?: string | null;
        time?: string | null;
        category?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteerBanner".
 */
export interface VolunteerBanner {
  heading: string;
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'volunteerBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteerContentBlock".
 */
export interface VolunteerContentBlock {
  heading: string;
  image: number | Media;
  paragraphs?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'volunteerContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteerBecameSection".
 */
export interface VolunteerBecameSection {
  sectionTitle: string;
  sectionDescription: string;
  volunteerSections: {
    title: string;
    description: string;
    image: number | Media;
    linkText: string;
    linkUrl: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'volunteerBecameSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workBanner".
 */
export interface WorkBanner {
  heading: string;
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workinchennai".
 */
export interface Workinchennai {
  heading: string;
  intro: string;
  description: string;
  items?:
    | {
        label: string;
        link: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workinchennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investBanner".
 */
export interface InvestBanner {
  heading: string;
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'investBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investChennai".
 */
export interface InvestChennai {
  heading: string;
  subHeading: string;
  description: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'investChennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investmentCategoryList".
 */
export interface InvestmentCategoryList {
  items: {
    title: string;
    subtitle?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    link?: string | null;
    id?: string | null;
  }[];
  backgroundImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'investmentCategoryList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liveBanner".
 */
export interface LiveBanner {
  heading: string;
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'liveBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livingInChennai".
 */
export interface LivingInChennai {
  heading: string;
  image: number | Media;
  paraZeroLiveSection: string;
  paraoneLiveSection: string;
  paraTwoLiveSection: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'livingInChennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chennaiLifeEssentials".
 */
export interface ChennaiLifeEssentials {
  heading: string;
  description: string;
  essentials?:
    | {
        text: string;
        link: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'chennaiLifeEssentials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accodomationBanner".
 */
export interface AccodomationBanner {
  heading: string;
  image: number | Media;
  breadcrumb?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accodomationBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotelInChennai".
 */
export interface HotelInChennai {
  sections: {
    title: string;
    description: string;
    image: number | Media;
    linkUrl?: string | null;
    linkText?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'HotelInChennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exploreMoreChennai".
 */
export interface ExploreMoreChennai {
  heading: string;
  description?: string | null;
  slides: {
    image: number | Media;
    title?: string | null;
    link?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'exploreMoreChennai';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitIntroText".
 */
export interface VisitIntroText {
  marqueeText?: string | null;
  title: string;
  highlightedText: string;
  description: string;
  showInstagramReels?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'visitIntroText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitBanner".
 */
export interface VisitBanner {
  title: string;
  bannerImage: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'visitBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  name: string;
  parent?: (number | null) | Page;
  slug: string;
  layout: (
    | {
        heading: string;
        title: string;
        description?: string | null;
        volunteerSlidesRef: number | VolunteerSlide;
        id?: string | null;
        blockName?: string | null;
        blockType: 'becameAVolunteer';
      }
    | {
        cards: {
          title: string;
          place: string;
          image: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'explore';
      }
    | {
        heading?: string | null;
        description?: string | null;
        images?:
          | {
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'startupChennai';
      }
    | {
        heading: string;
        subheading: string;
        cards: {
          title: string;
          place: string;
          image: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'funChennai';
      }
    | {
        heading: string;
        description: string;
        reelsRef: number | SocialReel;
        id?: string | null;
        blockName?: string | null;
        blockType: 'socialChennai';
      }
    | {
        placeholderText: string;
        buttonText: string;
        enableFilters?: boolean | null;
        filters?:
          | {
              label: string;
              options?:
                | {
                    value: string;
                    label: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'globalSearch';
      }
    | {
        heading: string;
        subheading?: string | null;
        categorySource?: (number | InvestmentCategory)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'chennaiInvestments';
      }
    | {
        heading: string;
        description?: string | null;
        eventGroupRef: number | EventGroup;
        id?: string | null;
        blockName?: string | null;
        blockType: 'events-calendar-block';
      }
    | {
        heading: string;
        image: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'volunteerBanner';
      }
    | {
        heading: string;
        image: number | Media;
        paragraphs?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'volunteerContentBlock';
      }
    | {
        sectionTitle: string;
        sectionDescription: string;
        volunteerSections: {
          title: string;
          description: string;
          image: number | Media;
          linkText: string;
          linkUrl: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'volunteerBecameSection';
      }
    | {
        heading: string;
        image: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workBanner';
      }
    | {
        heading: string;
        intro: string;
        description: string;
        items?:
          | {
              label: string;
              link: string;
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workinchennai';
      }
    | {
        heading: string;
        image: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'investBanner';
      }
    | {
        heading: string;
        subHeading: string;
        description: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'investChennai';
      }
    | {
        items: {
          title: string;
          subtitle?: string | null;
          description?: string | null;
          image?: (number | null) | Media;
          link?: string | null;
          id?: string | null;
        }[];
        backgroundImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'investmentCategoryList';
      }
    | {
        heading: string;
        image: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'liveBanner';
      }
    | {
        heading: string;
        image: number | Media;
        paraZeroLiveSection: string;
        paraoneLiveSection: string;
        paraTwoLiveSection: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'livingInChennai';
      }
    | {
        heading: string;
        description: string;
        essentials?:
          | {
              text: string;
              link: string;
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'chennaiLifeEssentials';
      }
    | {
        heading: string;
        image: number | Media;
        breadcrumb?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'accodomationBanner';
      }
    | {
        sections: {
          title: string;
          description: string;
          image: number | Media;
          linkUrl?: string | null;
          linkText?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'HotelInChennai';
      }
    | {
        heading: string;
        description?: string | null;
        slides: {
          image: number | Media;
          title?: string | null;
          link?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'exploreMoreChennai';
      }
    | {
        title: string;
        description?: string | null;
        items?: (number | VisitItem)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'visit-category';
      }
    | {
        marqueeText?: string | null;
        title: string;
        highlightedText: string;
        description: string;
        showInstagramReels?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'visitIntroText';
      }
    | {
        title: string;
        bannerImage: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'visitBanner';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitItems".
 */
export interface VisitItem {
  id: number;
  label: string;
  description?: string | null;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'volunteerSlides';
        value: number | VolunteerSlide;
      } | null)
    | ({
        relationTo: 'investment-categories';
        value: number | InvestmentCategory;
      } | null)
    | ({
        relationTo: 'eventGroups';
        value: number | EventGroup;
      } | null)
    | ({
        relationTo: 'social-reels';
        value: number | SocialReel;
      } | null)
    | ({
        relationTo: 'visitItems';
        value: number | VisitItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  slug?: T;
  layout?:
    | T
    | {
        becameAVolunteer?:
          | T
          | {
              heading?: T;
              title?: T;
              description?: T;
              volunteerSlidesRef?: T;
              id?: T;
              blockName?: T;
            };
        explore?:
          | T
          | {
              cards?:
                | T
                | {
                    title?: T;
                    place?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        startupChennai?:
          | T
          | {
              heading?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        funChennai?:
          | T
          | {
              heading?: T;
              subheading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    place?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        socialChennai?:
          | T
          | {
              heading?: T;
              description?: T;
              reelsRef?: T;
              id?: T;
              blockName?: T;
            };
        globalSearch?:
          | T
          | {
              placeholderText?: T;
              buttonText?: T;
              enableFilters?: T;
              filters?:
                | T
                | {
                    label?: T;
                    options?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        chennaiInvestments?:
          | T
          | {
              heading?: T;
              subheading?: T;
              categorySource?: T;
              id?: T;
              blockName?: T;
            };
        'events-calendar-block'?:
          | T
          | {
              heading?: T;
              description?: T;
              eventGroupRef?: T;
              id?: T;
              blockName?: T;
            };
        volunteerBanner?:
          | T
          | {
              heading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        volunteerContentBlock?:
          | T
          | {
              heading?: T;
              image?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        volunteerBecameSection?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              volunteerSections?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    linkText?: T;
                    linkUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        workBanner?:
          | T
          | {
              heading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        workinchennai?:
          | T
          | {
              heading?: T;
              intro?: T;
              description?: T;
              items?:
                | T
                | {
                    label?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        investBanner?:
          | T
          | {
              heading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        investChennai?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        investmentCategoryList?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    description?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        liveBanner?:
          | T
          | {
              heading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        livingInChennai?:
          | T
          | {
              heading?: T;
              image?: T;
              paraZeroLiveSection?: T;
              paraoneLiveSection?: T;
              paraTwoLiveSection?: T;
              id?: T;
              blockName?: T;
            };
        chennaiLifeEssentials?:
          | T
          | {
              heading?: T;
              description?: T;
              essentials?:
                | T
                | {
                    text?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accodomationBanner?:
          | T
          | {
              heading?: T;
              image?: T;
              breadcrumb?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        HotelInChennai?:
          | T
          | {
              sections?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    linkUrl?: T;
                    linkText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        exploreMoreChennai?:
          | T
          | {
              heading?: T;
              description?: T;
              slides?:
                | T
                | {
                    image?: T;
                    title?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'visit-category'?:
          | T
          | {
              title?: T;
              description?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        visitIntroText?:
          | T
          | {
              marqueeText?: T;
              title?: T;
              highlightedText?: T;
              description?: T;
              showInstagramReels?: T;
              id?: T;
              blockName?: T;
            };
        visitBanner?:
          | T
          | {
              title?: T;
              bannerImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteerSlides_select".
 */
export interface VolunteerSlidesSelect<T extends boolean = true> {
  title?: T;
  slides?:
    | T
    | {
        slug?: T;
        image?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        detailedContent?: T;
        video?: T;
        faq?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-categories_select".
 */
export interface InvestmentCategoriesSelect<T extends boolean = true> {
  name?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventGroups_select".
 */
export interface EventGroupsSelect<T extends boolean = true> {
  title?: T;
  events?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        time?: T;
        category?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-reels_select".
 */
export interface SocialReelsSelect<T extends boolean = true> {
  title?: T;
  reels?:
    | T
    | {
        thumbnail?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitItems_select".
 */
export interface VisitItemsSelect<T extends boolean = true> {
  label?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  footerSections: {
    mainFooterLogo?: (number | null) | Media;
    socialLinks?:
      | {
          platform: string;
          link: string;
          icon: number | Media;
          id?: string | null;
        }[]
      | null;
    digitalChennaiLinks?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    socialChennaiLinks?:
      | {
          title: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    funChennaiLinks?:
      | {
          title: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    startupChennaiLinks?:
      | {
          title: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    foodieChennaiLinks?:
      | {
          title: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    techChennaiLinks?:
      | {
          title: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    creativeChennaiLinks?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    businessChennaiLinks?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    networkChennaiLinks?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    usefulLinks?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    designByLogo: number | Media;
    footerText: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerSections?:
    | T
    | {
        mainFooterLogo?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              link?: T;
              icon?: T;
              id?: T;
            };
        digitalChennaiLinks?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        socialChennaiLinks?:
          | T
          | {
              title?: T;
              link?: T;
              id?: T;
            };
        funChennaiLinks?:
          | T
          | {
              title?: T;
              link?: T;
              id?: T;
            };
        startupChennaiLinks?:
          | T
          | {
              title?: T;
              link?: T;
              id?: T;
            };
        foodieChennaiLinks?:
          | T
          | {
              title?: T;
              link?: T;
              id?: T;
            };
        techChennaiLinks?:
          | T
          | {
              title?: T;
              link?: T;
              id?: T;
            };
        creativeChennaiLinks?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        businessChennaiLinks?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        networkChennaiLinks?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        usefulLinks?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        designByLogo?: T;
        footerText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}